In [2]:
import os
def cls():
    c = os.system('clear')
cls()

In [3]:
# Import the necessary libraries
import numpy as np

In [ ]:
LG = np.array([2, 3])  # (Numpy 1D array with 2 elements)
Pl = np.array([4, 5])
PG = LG + Pl
PG

In [5]:
Pl = np.array([[4, 5], [6, 7], [8, 9]])  # 2D array with 3 rows and two columns
PG = LG + Pl
PG

array([[ 6,  8],
       [ 8, 10],
       [10, 12]])

In [6]:
RGl = np.array([[np.cos(np.pi/4), -np.sin(np.pi/4)], [np.sin(np.pi/4), np.cos(np.pi/4)]])
Pl  = np.array([[1, 1]]).T  # transpose the array for correct matrix multiplication
PG = np.dot(RGl, Pl)        # the function dot() is used for matrix multiplication of arrays
np.around(PG, 4)            # round the number due to floating-point arithmetic errors

array([[ 0.    ],
       [ 1.4142]])

In [7]:
Pl  = np.array([[1, 1], [0, 1], [1, 0]]).T  # transpose array for matrix multiplication
PG = np.dot(RGl, Pl)  # the function dot() is used for matrix multiplication with arrays
np.around(PG, 4)      # round the number due to floating point arithmetic errors

array([[ 0.    , -0.7071,  0.7071],
       [ 1.4142,  0.7071,  0.7071]])

In [8]:
RGl = np.mat([[np.cos(np.pi/4), -np.sin(np.pi/4)], [np.sin(np.pi/4), np.cos(np.pi/4)]])
Pl  = np.mat([[1, 1], [0,1], [1, 0]]).T  # 2x3 matrix
PG = RGl*Pl       # matrix multiplication in NumPy
np.around(PG, 4)  # round the number due to floating point arithmetic errors

array([[ 0.    , -0.7071,  0.7071],
       [ 1.4142,  0.7071,  0.7071]])

$$x + 1 = \frac{x}{2}\,.$$
$$F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx\,.$$

In [10]:
from IPython.display import display, Math, Latex
display(Math(r'F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx'))

<IPython.core.display.Math object>

In [2]:
def f1(testvar):
    return 'f1:: {}'.format(testvar)

def f2(testvar):
    return 'f2:: {}'.format(testvar)

def f3(testvar):
    return 'f3:: {}'.format(testvar)

d = {
    'func1': f1,
    'func2': f2,
    'func3': f3,
}

In [4]:
d['func3']("Тятя")

'f3:: Тятя'

In [20]:
print(locals()['f1']('g'))
print(locals().get('f1')('ggg'))
#print(getattr(locals().get('f1'), 'f1'))('ggg')
#print(getattr(locals().get('f1'), 'f1'))
print(locals().get('f1'))

f1:: g
f1:: ggg
<function f1 at 0x7fddf8690730>


In [1]:
def tf(fn, data='', g=False):
    Fa_TYPES = {
        'func1': f1,
        'func2': f2,
        'func3': f3,
    }

    Fb_TYPES = {
        'func1': 'f1',
        'func2': 'f2',
        'func3': 'f3',
    }

    if g:
        return Fa_TYPES[fn](data)
#         return globals().get(Fb_TYPES[fn])(data)
    else:
        return globals()[Fb_TYPES[fn]](data)

def f1(data):
    return('a:: {}'.format(data))

def f2(data):
    return('b:: {}'.format(data))

def f3(data):
    return('c:: {}'.format(data))

def testf():
    for q in range (3000000):
        h = tf('func1', data=str(q), g=True)

In [2]:
%%time
testf()

CPU times: user 7.62 s, sys: 56.9 ms, total: 7.68 s
Wall time: 7.77 s


In [3]:
import pandas as pd

In [4]:
df = pd.Series([(g+1)*(g+2)*(g+3) % 256 for g in range(1000000)])

print(len(df))
print(len(df.index))
print(df.count())
print(df.size)

1000000
1000000
1000000
1000000


In [5]:
%%timeit
df.count()

100 loops, best of 3: 7.19 ms per loop


In [31]:
# import math
# from math import *
cosx = math.cos

In [38]:
%%timeit
for i in range(100):
    h = cosx(1/(i+1.))

10000 loops, best of 3: 42.6 µs per loop
